### ISSUE TITLE
java.lang.RuntimeException: Could not start process: <EOF>

### ISSUE THREAD

**Issue by BarraR3port** [svenkubiak/embedded-mongodb#4]
I run into this error when initializating the project:

```
[12:54:51 ERROR]: Error occurred while enabling VirtualPinataCore v1.8 (Is it up to date?)
java.lang.RuntimeException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:81) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:115) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:54) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) ~[VirtualPinataCore-1.8.jar:?]
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109) ~[VirtualPinataCore-1.8.jar:?]
        at de.svenkubiak.embeddedmongodb.EmbeddedMongoDB.start(EmbeddedMongoDB.java:111) ~[VirtualPinataCore-1.8.jar:?]
        at net.lymarket.comissionss.virtualpinata.Main.onEnable(Main.java:132) ~[VirtualPinataCore-1.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1602]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by svenkubiak** [comment]
Thanks for reporting this. Let me look into this.

**Comment by svenkubiak** [comment]
Could you provide some more information:

- Which Java version do you use?
- Which version of embeeded-mongo are you using?
- Are you connected to the internet? - flapdoople needs to download the latest embeeded version
- Which OS are you running?

Referencing https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232

**Comment by Soggywaters** [comment]
I'm seeing the same error on my side and here's what I'm using: 

Java version: 11
EmbeddedMongo: v3.6.2
Running on Windows 11
And yes, I am connected to the internet cause I can see the embedded mongo download: 

`2022-09-30 13:25:52.096  INFO [,,] 5556 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{3.6.2}:Platform{operatingSystem=Windows, architecture=X86_64} : 90 %

2022-09-30 13:28:45.874  INFO [,,] 5556 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{3.6.2}:Platform{operatingSystem=Windows, architecture=X86_64} : 100 %

2022-09-30 13:28:45.874  INFO [,,] 5556 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{3.6.2}:Platform{operatingSystem=Windows, architecture=X86_64} : downloaded with 172kb/s`

Additionally, I'm using: 

de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.4.11
org.springframework.boot:spring-boot-starter-data-mongodb:2.6.6

**Comment by michaelmosmann** [comment]
@Soggywaters .. hmm.. i will try to reproduce this.. have to reactivate my windows pc for this..

**Comment by svenkubiak** [comment]
@Soggywaters Spring boot ships with its own embeeded mongodb. This library is not required if using Spring Boot and having both on the classplath will probably not work. If using Spring Boot, then using


```
<dependency>
<groupId>de.flapdoodle.embed</groupId>
<artifactId>de.flapdoodle.embed.mongo</artifactId>
</dependency>
```


should be sufficent.
